### ISSUE TITLE
Should be able edit estimated flight time as runway departures and approaches affect the time.

### ISSUE THREAD

**Issue by Rotex43** [xairline/xairline#11]

**Comment by zodiac1214** [comment]
@Rotex43 does it make sense to calculate flight time by your take off time to landing time? I don't think it's a good idea to allow changing of estimated time because in real world airlines don't change that :) 

So i am thinking this as bug where the flight time is to tight because i take it from the moment you start taxing to the moment you slowed down after landing. Maybe I should do one of the two:

1. add 20-30min to caculated flight time, kind of what real life airlines do?
2. caculate flight time based on your takeoff and touchdown time?

What do you think?

**Comment by Rotex43** [comment]
Agree adding a buffer would be a good idea

**Comment by Rotex43** [comment]
Noticed on a flight from KSFO to CYVR airline (Air Canada) estimated time enroute as 2:10 program estimate was 1:45 (1.77), my flight was 1.86 Hr

**Comment by zodiac1214** [comment]
> Noticed on a flight from KSFO to CYVR airline (Air Canada) estimated time enroute as 2:10 program estimate was 1:45 (1.77), my flight was 1.86 Hr

I think, it is another bug. when i call some 3rd party api, it askes for type of aircraft...so if you use 787 vs 737...I think i hard coded it for 737, one more thing to fix here
